export const AmongNadsABI = [
  {
    type: "constructor",
    inputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancelGame",
    inputs: [{ name: "gameId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancelGameByTimeout",
    inputs: [{ name: "gameId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimPayout",
    inputs: [{ name: "gameId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimRefund",
    inputs: [{ name: "gameId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "deposit",
    inputs: [],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "getBet",
    inputs: [
      { name: "gameId", type: "uint256", internalType: "uint256" },
      { name: "bettor", type: "address", internalType: "address" },
    ],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct IAmongNads.Bet",
        components: [
          { name: "bettor", type: "address", internalType: "address" },
          { name: "team", type: "uint8", internalType: "enum IAmongNads.Team" },
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "claimed", type: "bool", internalType: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getGame",
    inputs: [{ name: "gameId", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct IAmongNads.Game",
        components: [
          { name: "id", type: "uint256", internalType: "uint256" },
          {
            name: "state",
            type: "uint8",
            internalType: "enum IAmongNads.GameState",
          },
          { name: "bettingDeadline", type: "uint256", internalType: "uint256" },
          { name: "totalPool", type: "uint256", internalType: "uint256" },
          { name: "crewmatesPool", type: "uint256", internalType: "uint256" },
          { name: "impostorsPool", type: "uint256", internalType: "uint256" },
          { name: "crewmatesSeed", type: "uint256", internalType: "uint256" },
          { name: "impostorsSeed", type: "uint256", internalType: "uint256" },
          {
            name: "winningTeam",
            type: "uint8",
            internalType: "enum IAmongNads.Team",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasBets",
    inputs: [{ name: "gameId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasUserBets",
    inputs: [{ name: "gameId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "initialize",
    inputs: [
      { name: "initialOwner", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "placeBet",
    inputs: [
      { name: "gameId", type: "uint256", internalType: "uint256" },
      { name: "team", type: "uint8", internalType: "enum IAmongNads.Team" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "seedPool",
    inputs: [
      { name: "gameId", type: "uint256", internalType: "uint256" },
      { name: "crewAmount", type: "uint256", internalType: "uint256" },
      { name: "impAmount", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setLobbyDuration",
    inputs: [{ name: "newDuration", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setSettlementTimeout",
    inputs: [{ name: "newTimeout", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "settleGame",
    inputs: [
      { name: "gameId", type: "uint256", internalType: "uint256" },
      {
        name: "winningTeam",
        type: "uint8",
        internalType: "enum IAmongNads.Team",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "sweep",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "to", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "upgradeToAndCall",
    inputs: [
      { name: "newImplementation", type: "address", internalType: "address" },
      { name: "data", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
] as const;
